### PR TITLE
Todo-27 AddTodo TodoList-24 TodoItem-25 todoPage-43

### PR DESCRIPTION
**Pull request by meital10**
without styling and without checkbox+3 dots. added also styles.css and model.tsx

### CODE REVIEW

**Comment by OrSamu** [comment]
I think every component should be in a different folder inside the main components folder.

**Comment by meital10** [comment]
They are. There are different folders for each component in the project. I just stayed in one branch instead of changing every time (because they are connected)

**Comment by meital10** [comment]
I mean different file for each component in the componenets folder. Do you mean to separate them for folders for each file? why?

**Comment by OrSamu** [comment]
The branch for all the changes is fine (at least **I** think its fine),
Adding a print screen from my side just to make sure:
image
The files: AddTodo,TodoItem,TodoPage,Todoist and styles shouldn't be there

**Comment by meital10** [comment]
If you're not sure you can cheack it to see if it is fine :)
It is a small application. I can do it but I dont think that we need to make folder for each file. There are all files in the components folder.
I think it is a structure issue to decide in a team meeting

**Comment by meital10** [comment]
I fixed it. can you please check it again? Thanks

**Pull request merged**
